name: schrodle
description: "Schrodle is a game that is inspired by Wordle and the Schrödinger's Cat thought experiment."
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  bloc: ^8.1.3
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  meta: ^1.10.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.11
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/lexicon/
  fonts:
    - family: Courier Prime
      fonts:
        - asset: assets/fonts/Courier_Prime/CourierPrime-Regular.ttf
        - asset: assets/fonts/Courier_Prime/CourierPrime-Bold.ttf
        - asset: assets/fonts/Courier_Prime/CourierPrime-Italic.ttf
          style: italic
        - asset: assets/fonts/Courier_Prime/CourierPrime-BoldItalic.ttf
          style: italic
